name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [check, lint, test, build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pipeline
        uses: ./.github/actions/setup-pipeline
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run check
        if: matrix.task == 'check'
        run: pnpm run check

      - name: Run lint
        if: matrix.task == 'lint'
        run: pnpm run lint

      - name: Run tests
        if: matrix.task == 'test'
        run: pnpm test
        env:
          NODE_ENV: test

      - name: Build web
        if: matrix.task == 'build'
        run: npx nx build web
        env:
          NODE_ENV: production
